// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;
